[package]
name = "rubikmaster"
version = "0.1.0"
authors = ["Akira Hayakawa <ruby.wktk@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
once_cell = "1.8"
nom = "7"
rand = "0.8"

[dev-dependencies]
proptest = "1.0"
nalgebra = "*"